# Site Configuration
repository: jcapron/me
favicon: images/favicon.ico

# Content Version
version: 2

# Personal Information
name: Julien Capron
title: Senior Director of Engineering
email: contact@juliencapron.com
blog: www.juliencapron.com/blog

# User Interface Settings
darkmode: false

# Social Media Profiles
github_username: jcapron
linkedin_username: juliencapron

# About Section
about_profile_image: images/profile.png
about_content: |
  Welcome! I'm Julien Capron, a Senior Director of Engineering with a passion for product innovation, team building, and process optimization. My journey in the tech industry is marked by a relentless pursuit of excellence and a proactive, solution-focused approach. Here, I share my professional experiences and insights.

# Projects and Professional Experience
content:
  - title: Projects
    layout: list
    content:
      - layout: left
        title: Know Thy Neighbor
        quote: >
          Transforming a simple company directory into a competitive, engaging quiz game.
        description: |
          Know Thy Neighbor, originally a straightforward company directory, transformed into an engaging quiz game, strengthening team bonds and becoming an integral part of our onboarding process.

      - layout: left
        title: Hack Day
        quote: >
          Fostering innovation and camaraderie through a company-wide hackathon.
        description: |
          I spearheaded Hack Day, a company-wide hackathon fostering creativity and teamwork. This platform I maintained allows team members to showcase innovative projects and celebrate collective ingenuity.

      - layout: left
        title: Jira Master
        quote: >
          Streamlining team efficiency with custom Jira dashboard implementations.
        description: |
          In Jira Master, I integrated custom dashboards to streamline project tracking, enhancing our team's efficiency and effectiveness in managing complex projects.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Storyblocks
        link: storyblocks.com
        sub_title: Senior Director of Engineering
        caption: January 2023 - Present
        quote: >
          Elevating organizational performance through strategic leadership and innovation.
        description: |
          In my tenure as Senior Director, I expanded my leadership to the Data Science team, significantly impacting key business metrics. My work championing Core Web Vitals led to notable improvements in site performance. Additionally, my leadership in nurturing team dynamics and implementing effective performance management practices has substantially increased productivity and accountability across teams.

      - layout: left
        sub_title: Director of Engineering
        caption: December 2021 - December 2022
        quote: >
          Spearheading transformative change and fostering a growth-oriented culture.
        description: |
          During my initial year at Storyblocks, I led pivotal initiatives, significantly enhancing our engineering processes and team culture. My efforts in the Delivery workstream brought about notable improvements in cross-functional collaboration and project execution. A key focus was cultivating trust and strong relationships, which greatly boosted team morale and efficiency.

      - layout: left
        title: CB Insights
        link: cbinsights.com
        sub_title: Director of Engineering
        caption: October 2019 - November 2021
        quote: >
          Leading with innovation and a strategic focus.
        description: |
          As Director at CB Insights, I nurtured leadership skills within the team and collaborated closely on product strategy. I spearheaded initiatives like Day Aways, revised the engineering career framework, and introduced comprehensive onboarding processes, contributing significantly to a culture of innovation and strategic execution.

      - layout: left
        sub_title: Engineering Manager
        caption: January 2017 - September 2019
        quote: >
          Managing and growing high-performing engineering teams.
        description: |
          In my role as Engineering Manager, I was instrumental in scaling the team and introducing fully remote teams. I focused on leadership development and managed our Engineering events budget, contributing significantly to team growth and cohesion.

      - layout: left
        sub_title: Full Stack Developer
        caption: June 2015 - December 2016
        quote: >
          Technical contributions in back-end development.
        description: |
          As a Full Stack Developer, my work involved enhancing database search capabilities and developing an ETL framework, which was crucial in driving significant annual revenue.

      - layout: left
        title: PINCHme
        link: pinchme.com
        sub_title: Ruby on Rails Developer
        caption: March 2014 - June 2015
        quote: >
          Full-stack development in a dynamic startup environment.
        description: |
          At PINCHme, I worked on optimizing the user experience and implementing features that significantly impacted the company's product distribution and marketing strategies.

      - layout: left
        title: Jumblzar
        link: jumblzar.com
        sub_title: Ruby on Rails Developer
        caption: April 2013 - February 2014
        quote: >
          Developing core features in an early-stage startup.
        description: |
          My time at Jumblzar was marked by significant contributions to the platform's development, including implementing a CMS, enhancing user engagement features, and optimizing the user interface.

      - layout: left
        title: Desknet
        link: desknetinc.com
        sub_title: Technical Consultant
        caption: May 2012 - January 2013
        quote: >
          Delivering enterprise solutions through technical consultancy.
        description: |
          As a Technical Consultant at Desknet, I played a pivotal role in analyzing customer requirements and delivering dynamic enterprise publishing solutions.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Stevens Institute of Technology
        caption: 2011
        sub_title: Master's degree, Information Systems
        quote: >
          Advanced studies in Information Systems.
        description: |
          My studies at Stevens focused on IT management, organizational design, and technology integration. I also contributed as a Research Assistant on a project for the US Army using Unity for war game simulations.

      - layout: left
        title: EPITA
        caption: 2006 - 2011
        sub_title: Master's Degree, Computer Science, Telecommunications
        quote: >
          Comprehensive engineering education in Computer Science and Telecommunications.
        description: |
          At EPITA, I gained a solid foundation in telecommunications, networks, and computer science, balancing technical expertise with interpersonal skills.

  - title: A Little More About Me
    layout: text
    content: |
      Beyond my professional life, I am deeply passionate about Dungeons and Dragons, pro wrestling, and gardening. These hobbies reflect my love for strategy, performance, and nurturing growth, both in and out of the workplace.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme
# https://sproogen.github.io/modern-resume-theme/
sass:
  sass_dir: _sass
  style: compressed
plugins:
 - jekyll-seo-tag
